

import java.util.ArrayList;




public class Fenetre_Questions extends javax.swing.JFrame {

    private int indexQuestionCourante = 0;
    private int scoreValue = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fenetre_Questions.class.getName());
    private ArrayList<Questions> ListeQuestions = new ArrayList<>();

    /**
     * Creates new form FenetreQuizz
     */
    public Fenetre_Questions() {
        initComponents();

        ListeQuestions.add(new Questions(
                "Quelle est la capitale de la France ?",
                "Lyon",
                "Paris",
                "Marseille",
                "Bordeaux",
                2));
        ListeQuestions.add(new Questions(
                "Quelle est la capitale de l'Italie ?",
                "Rome",
                "Milan",
                "Naples",
                "Turin",
                1
        ));

        ListeQuestions.add(new Questions(
                "Quel est le symbole chimique de l’eau ?",
                "O2",
                "H2O",
                "CO2",
                "HO",
                2
        ));

        ListeQuestions.add(new Questions(
                "En quelle année a eu lieu la Révolution française ?",
                "1515",
                "1789",
                "1914",
                "1848",
                2
        ));

        ListeQuestions.add(new Questions(
                "Combien font 7 × 8 ?",
                "48",
                "54",
                "56",
                "64",
                3
        ));

        ListeQuestions.add(new Questions(
                "Quel est l’océan le plus vaste ?",
                "Atlantique",
                "Indien",
                "Pacifique",
                "Arctique",
                3
        ));

        ListeQuestions.add(new Questions(
                "Quel pays a remporté la Coupe du monde de football 2018 ?",
                "Allemagne",
                "France",
                "Brésil",
                "Argentine",
                2
        ));

        ListeQuestions.add(new Questions(
                "Quel est l’élément le plus léger du tableau périodique ?",
                "Hydrogène",
                "Hélium",
                "Lithium",
                "Carbone",
                1
        ));

        ListeQuestions.add(new Questions(
                "Qui a peint la Joconde ?",
                "Picasso",
                "Van Gogh",
                "Monet",
                "Leonard de Vinci",
                4
        ));

        ListeQuestions.add(new Questions(
                "Quelle est la planète la plus proche du Soleil ?",
                "Vénus",
                "Mercure",
                "Terre",
                "Mars",
                2
        ));
java.util.Collections.shuffle(ListeQuestions);

        afficherQuestionCourante();

    }

    private void afficherQuestionCourante() {
        Questions q = ListeQuestions.get(indexQuestionCourante);
q.melangerReponses();

        // Construire un énoncé complet
        String texte
                = "<html>"
                + q.getIntitule() + "<br><br>"
                + "A) " + q.getProposition1() + "<br>"
                + "B) " + q.getProposition2() + "<br>"
                + "C) " + q.getProposition3() + "<br>"
                + "D) " + q.getProposition4()
                + "</html>";

        jLabel3.setText(texte);

        // Les boutons restent A, B, C, D → aucun changement
        // Réactiver les boutons
        A.setEnabled(true);
        C.setEnabled(true);
        C.setEnabled(true);
        D.setEnabled(true);

        // Effacer l’ancienne réponse affichée
        reponsecorrecte.setText("");
    }

    private void verifierReponse(int choixUtilisateur) {
 
        Questions q = ListeQuestions.get(indexQuestionCourante);

        // Vérifier si le choix correspond à la bonne réponse
        if (choixUtilisateur == q.getIndexBonneReponse()) {
            scoreValue++;  // On incrémente
            textscore.setText(String.valueOf(scoreValue)); // Met à jour l’affichage du score
            reponsecorrecte.setText("Bonne réponse !");


        } else {
            reponsecorrecte.setText(
    "Mauvaise réponse ! La bonne réponse était : "
    + getLettreBonneReponse(q.getIndexBonneReponse())
);
 
        }

       
        // Désactiver les boutons après la réponse
        A.setEnabled(false);
        C.setEnabled(false);
        C.setEnabled(false);
        D.setEnabled(false);
       
   
    }
    private String getLettreBonneReponse(int index) {
    switch (index) {
        case 1: return "A";
        case 2: return "B";
        case 3: return "C";
        case 4: return "D";
        default: return "?";
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        A = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        B = new javax.swing.JButton();
        textscore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reponsecorrecte = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Questions :");

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        textscore.setText("Score:      ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("L'énoncé");

        reponsecorrecte.setText("Une ou Plusieurs ou aucune bonne Réponse");

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        score.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(next)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reponsecorrecte, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(56, 56, 56)
                                .addComponent(B)
                                .addGap(85, 85, 85)
                                .addComponent(C)
                                .addGap(50, 50, 50)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textscore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textscore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(score))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reponsecorrecte)
                    .addComponent(next))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
       verifierReponse(1);
    }//GEN-LAST:event_AActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        verifierReponse(4);
      
    }//GEN-LAST:event_DActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
       verifierReponse(2); 
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
verifierReponse(3);        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
          // Passer à la question suivante
        indexQuestionCourante++;

        // Vérifier si on est encore dans les limites de la liste
        if (indexQuestionCourante < ListeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            // PLUS AUCUNE QUESTION → fin du quiz
            jLabel3.setText("<html><h3>Quiz terminé !</h3><br>Score final : "
                    + scoreValue + " / " + ListeQuestions.size() + "</html>");

            // Désactiver les boutons
            A.setEnabled(false);
            B.setEnabled(false);
            C.setEnabled(false);
            D.setEnabled(false);

            // Désactiver le bouton Question suivante
            next.setEnabled(false);

            // Facultatif : Effacer réponse correcte
            reponsecorrecte.setText("");
        } // TODO add your handling code here:
    
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fenetre_Questions().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton next;
    private javax.swing.JLabel reponsecorrecte;
    private javax.swing.JLabel score;
    private javax.swing.JLabel textscore;
    // End of variables declaration//GEN-END:variables
}